baseURL = "http://yabirgb.com/"
languageCode = "en-us"
title = "Yábir García"
theme = "cocoa"
canonifyurls = true


[permalinks]
blog = "blog/:slug/"

[[menu.main]]
name                   = "Home"
weight                 = 1
identifier             = "home"
url = "/"

[[menu.main]]
name                   = "Blog"
weight                 = 2
identifier             = "blog"
url = "/blog/"


[params]
latestpostscount       = 5                             # how many posts to display on the home page
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
disableRSS 	       = true 	       
#email                  = "contact@yabirgb.com"
#github                 = "//github.com/yabirgb"
#lang                   = "en"
#linkedin               = "//linkedin.com/in/you"
#twitter                = "//twitter.com/yabirgb"
#mastodon 	       = "//mstdn.io/@yabirgb"